# Generated by Django 4.0.5 on 2022-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QUESTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('q1', models.CharField(max_length=500)),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.CharField(max_length=500)),
                ('q4', models.CharField(max_length=500)),
                ('q5', models.CharField(max_length=500)),
                ('q6', models.CharField(max_length=500)),
                ('q7', models.CharField(max_length=500)),
                ('q8', models.CharField(max_length=500)),
                ('q9', models.CharField(max_length=500)),
                ('content', models.IntegerField(default=9)),
                ('tech', models.IntegerField(default=9)),
                ('design', models.IntegerField(default=9)),
                ('cultural', models.IntegerField(default=9)),
                ('creativity', models.IntegerField(default=9)),
                ('hospitality', models.IntegerField(default=9)),
                ('logistics', models.IntegerField(default=9)),
            ],
        ),
    ]
