# Generated by Django 4.0.5 on 2022-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q5',
        ),
        migrations.AlterField(
            model_name='question',
            name='q1',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='q2',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='q3',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='q4',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='q6',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='q7',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='q8',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='q9',
            field=models.CharField(max_length=900),
        ),
    ]
